[package]
name = "localstack-rust-example"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.14.2"
serde_json = "1.0.140"
tokio = { version = "1.46.0", features = ["macros"] }

[profile.release]
lto = "fat"
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = "symbols"
